name: Build WoeUSB-ng AppImage

on:
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Step 2: Setup Python 3.10 (prebuilt wxPython wheels exist)
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install system build dependencies
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential curl xz-utils patchelf \
            libgtk-3-dev libjpeg-dev libtiff-dev libpng-dev libexpat1-dev libcurl4-openssl-dev \
            libx11-dev libxext-dev libxinerama-dev libxcursor-dev libxrandr-dev libxi-dev

      # Step 4: Install Python packages (prebuilt wheels)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --prefix=$HOME/.local --only-binary=:all: \
            wxPython termcolor build installer

      # Step 5: Make AppImage script executable
      - name: Make AppImage script executable
        run: chmod +x pkg/appimage.sh

      # Step 6: Run AppImage build
      - name: Build AppImage
        run: pkg/appimage.sh

      # Step 7: Upload resulting AppImage
      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: woeusb-ng-appimage
          path: pkg/woeusb-ng-build/WoeUSB-ng-x86_64.AppImage
