name: Build WoeUSB-ng AppImage (Arch)

on:
  workflow_dispatch:

jobs:
  build-appimage:
    # run the job inside an Arch Linux container
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Refresh pacman DB and install build dependencies
        run: |
          # pacman runs as root inside the container; --noconfirm to avoid prompts
          pacman -Syu --noconfirm

          pacman -S --noconfirm \
            base-devel \
            python \
            python-pip \
            python-virtualenv \
            python-setuptools \
            python-wheel \
            python-wxpython \
            wget \
            xz \
            patchelf \
            gtk3 \
            libjpeg-turbo \
            libtiff \
            libpng \
            expat \
            curl \
            libx11 \
            libxext \
            libxinerama \
            libxcursor \
            libxrandr \
            libxi \
            fuse2 \
            git

          # upgrade pip and install python build tools that Debian provided via apt
          pip install --upgrade pip build

      - name: Make AppImage script executable
        run: chmod +x pkg/appimage.sh

      - name: Build AppImage
        run: pkg/appimage.sh

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: woeusb-ng-appimage
          path: WoeUSB-ng-build/**/*.AppImage
