name: Build WoeUSB-ng AppImage

on:
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Step 2: Install build dependencies
      - name: Install build dependencies
        run: |
          python --version
          python3 --version
          sudo apt update
          sudo apt install -y \
            python3-pip python3-venv python3-setuptools python3-wheel \
            build-essential curl xz-utils patchelf \
            libgtk-3-dev libjpeg-dev libtiff-dev libpng-dev libexpat1-dev libcurl4-openssl-dev \
            libx11-dev libxext-dev libxinerama-dev libxcursor-dev libxrandr-dev libxi-dev

      # Step 3: Make AppImage script executable
      - name: Make AppImage script executable
        run: |
          chmod +x pkg/appimage.sh

      # Step 4: Install prebuilt wxPython wheel
      - name: Install wxPython
        run: |
          python3 -m pip install --upgrade pip setuptools wheel

          # Set wxPython version and wheel filename
          WX_VERSION=4.2.3
          PYTHON_TAG=cp312
          WHEEL_FILE=wxPython-${WX_VERSION}-${PYTHON_TAG}-${PYTHON_TAG}-linux_x86_64.whl

          # Download and install the wheel
          curl -L -o $WHEEL_FILE \
            https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/$WHEEL_FILE
          python3 -m pip install $WHEEL_FILE

      # Step 5: Run AppImage build
      - name: Build AppImage
        run: pkg/appimage.sh

      # Step 6: Upload resulting AppImage
      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: woeusb-ng-appimage
          path: pkg/woeusb-ng-build/WoeUSB-ng-x86_64.AppImage
